version: '2'
networks:
  ddn:
    external: true
services:
  springboot-microservice-discovery:
    container_name: springboot-microservice-discovery
    image: https://dockerreg.local:5000/springboot-microservice-discovery:latest
    restart: always
    #volumes:
    #        -  /root/UM/maccess/:/opt/storage/UM/maccess
    environment:
      - SPRING_PROFILES_ACTIVE=native,prod
    #        - DB_HOST=172.16.170.108:3306
    #        - DB_USER=root
    #        - DB_PASS=asd123ASD!@#
    ports:
      - '0.0.0.0:7000:7000'
    networks:
      - ddn