FROM https://dockerreg.local:5000/openjdk:13-alpine
RUN apk add --no-cache tzdata
ENV TZ Asia/Tehran
RUN addgroup -S spring && adduser -S spring -G spring
RUN mkdir -p /logs
ARG JAR_FILE=target/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-Dspring.profiles.active=dev","-jar","/app.jar"]